version: "3.7"

services:
  web:
    build: services/web
    command: python manage.py run -h 0.0.0.0
    environment:
      - FLASK_APP=project/__init__.py
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    image: web
